services:
  database:
    image: mysql:latest
    ports:
      - "${MQAF_DB_PORT:-3307}:3306"
    # command: --init-file /data/application/init.sql
    volumes:
      - ./docker-configuration/mysql/init.sql:/data/application/init.sql
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ddb
      MYSQL_DATABASE: ${MQAF_DB_DATABASE:-ddb}
      MYSQL_USER: ${MQAF_DB_USER:-ddb}
      MYSQL_PASSWORD: ${MQAF_DB_PASSWORD:-ddb}
    container_name: ${MQAF_DB_CONTAINER:-mqaf-ddb-db}
    networks:
      - mqaf-ddb

  solr:
    image: solr:9.6.1
    ports:
      - "${MQAF_SOLR_PORT:-8983}:8983"
    volumes:
      # Create directory up front with the right permissions, eg.:
      # mkdir ./solr-data && sudo chown -R 8983:8983 ./solr-data && sudo chmod -R 777 ./solr-data
      - ${MQAF_SOLR_DATA:-./solr-data}:/var/solr/data
      - ${MQAF_SOLR_ENTRY:-./docker-configuration/solr}:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:8983",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    restart: on-failure
    container_name: ${MQAF_SOLR_CONTAINER:-mqaf-ddb-solr}
    networks:
      - mqaf-ddb

  cli:
    image: ${MQAF_CLI_IMAGE:-ghcr.io/pkiraly/metadata-qa-ddb:main} # the name of the image
    volumes:
      - ./${DDB_INPUT:-test-ddb/input}:/opt/metadata-qa-ddb/input
      - ./${DDB_OUTPUT:-test-ddb/output}:/opt/metadata-qa-ddb/output
    # ports:
    #  - ${WS_WEBPORT:-8080}:8080             # Tomcat address
    environment:
      REPORT_WEBHOST: ${REPORT_WEBHOST:-localhost}
      REPORT_WEBPORT: ${REPORT_WEBPORT:-90}
      MQAF_DATA: ${MQAF_DATA:-}

      # FTP settings
      MQAF_FTP_USER: ${MQAF_FTP_USER:-}
      MQAF_FTP_PW: ${MQAF_FTP_PW:-}

      # MySQL setting
      MQAF_DB_HOST: ${MQAF_DB_HOST:-mqaf-ddb-db}
      MQAF_DB_PORT: 3306
      MQAF_DB_DATABASE: ${MQAF_DB_DATABASE:-ddb}
      MQAF_DB_USER: ${MQAF_DB_USER:-ddb}
      MQAF_DB_PASSWORD: ${MQAF_DB_PASSWORD:-ddb}

      # Solr settings
      MQAF_SOLR_HOST: ${MQAF_SOLR_HOST:-mqaf-ddb-solr}
      MQAF_SOLR_PORT: ${MQAF_SOLR_PORT:-8983}
      MQAF_SOLR_CORE_PREFIX: ${MQAF_SOLR_CORE_PREFIX:-ddb-qa}

      # extra validation paramteres
      MQAF_VALIDATION_PARAMS: ${MQAF_VALIDATION_PARAMS:-}
    container_name: ${MQAF_CLI_CONTAINER:-mqaf-ddb-cli}
    depends_on:
      - database
      - solr
    networks:
      - mqaf-ddb

  report:
    image: ${MQAF_REPORT_IMAGE:-ghcr.io/pkiraly/metadata-qa-ddb-web:v2.0}
    ports:
      - ${MQAF_REPORT_WEBPORT:-90}:80
      # - ${SOLRPORT:-8983}:8983
    volumes:
      - ${DDB_CONFIG:-./test-ddb/config}:/var/www/html/config
      - ${DDB_INPUT:-./test-ddb/input}:/opt/metadata-qa-ddb/input
      - ${DDB_OUTPUT:-./test-ddb/output}:/opt/metadata-qa-ddb/output
    environment:
      # MySQL settings
      MQAF_DB_HOST: ${MQAF_DB_HOST:-mqaf-ddb-db}
      MQAF_DB_PORT: 3306
      MQAF_DB_DATABASE: ${MQAF_DB_DATABASE:-ddb}
      MQAF_DB_USER: ${MQAF_DB_USER:-ddb}
      MQAF_DB_PASSWORD: ${MQAF_DB_PASSWORD:-ddb}

      # Apache Solr settings
      MQAF_SOLR_HOST: ${MQAF_SOLR_HOST:-mqaf-ddb-solr}
      MQAF_SOLR_PORT: ${MQAF_SOLR_PORT:-8983}
    container_name: ${MQAF_REPORT_CONTAINER:-mqaf-ddb-report}
    depends_on:
      - database
      - solr
    networks:
      - mqaf-ddb

networks:
  mqaf-ddb:

volumes:
  ddb-data:
    external: true
